//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblio.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class BiblioTB
    {
        public int ID { get; set; }
        public string Libro { get; set; }
        public string Genero { get; set; }
    }
}
